<div class="panel panel-default customize-panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-education"> </span> Wykształcenie
        </h3>
    </div>
    <div class="text-right">
        <a class="btn btn-primary" href="<?php echo $this->url('data', array('action' => 'addEducation')); ?>">Dodaj
            wykształcenie</a>
    </div>
    <div class="panel-body">
        <div class="customize-box-wrapper table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Nazwa szkoły</th>
                    <th>Od</th>
                    <th>Do</th>
                    <th>Akcja</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($educations as $education) : ?>
                    <tr>
                        <td class="col-md-6"><?php echo $education->school_name; ?></td>
                        <td class="col-md-3"><?php echo $education->date_from; ?></td>
                        <td class="col-md-3"><?php echo $education->date_to; ?></td>

                        <td>
                            <a href="<?php echo $this->url('data', array('action' => 'editEducation', 'id' => $education->idEducation)); ?>"
                               class="glyphicon glyphicon-edit"></a>
                            <a onclick="return confirm('Czy jesteś pewien, że chcesz usunąć?')"
                               href="<?php echo $this->url('data', array('action' => 'deleteEducation', 'id' => $education->idEducation)); ?>"
                               class="glyphicon glyphicon-remove-circle"></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

