<div class="panel panel-default customize-panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-pencil"> </span> Tworzenie testu
        </h3>
    </div>
    <div class="panel-body">
        <div class="customize-box-wrapper">
            <?php
            $helper = new \Application\View\Helper\Helper();

            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('idTest'));
            ?>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('advertisement')); ?>
                <div class="col-md-6">
                    <?php echo $this->formSelect($form->get('advertisement')); ?>
                    <?php echo $helper->formError($this, $form, 'advertisement'); ?>
                </div>
            </div>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('name')); ?>
                <div class="col-md-6">
                    <?php echo $this->formInput($form->get('name')); ?>
                    <?php echo $helper->formError($this, $form, 'name'); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('description')); ?>
                <div class="col-md-6">
                    <?php echo $this->formElement($form->get('description')); ?>
                    <?php echo $helper->formError($this, $form, 'description'); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('time')); ?>
                <div class="col-md-6">
                    <?php echo $this->formElement($form->get('time')); ?>
                    <?php echo $helper->formError($this, $form, 'time'); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('password')); ?>
                <div class="col-md-6">
                    <?php echo $this->formElement($form->get('password')); ?>
                    <?php echo $helper->formError($this, $form, 'password'); ?>
                </div>
            </div>

            <h4 class="text-center">Pytania testowe</h4>

            <div class="one-question" style="border-bottom: 1px solid #dbdbdb; margin: 5px 100px">
                <div class="form-group">
                    <?php $questionId = 0; ?>

                    <fieldset class="type">
                        <label class="col-md-4 control-label" for="question">Wybierz rodzaj pytania*</label>

                        <div class="col-md-6">
                            <div class="col-6-lg">
                                <select class="form-control" id="">
                                    <option value="0">otwarte</option>
                                    <option value="1">polotwarte</option>
                                    <option value="2">zamkniete</option>
                                </select>
                            </div>
                        </div>
                        <div class="open">
                            <label class="col-md-4 control-label" for="question">Pytanie*</label>

                            <div class="col-md-6">
                                <div class="col-6-lg">
                                    <input type="text" class="form-control"
                                           name="questions-open[<?php echo $questionId; ?>][question]" id=""/>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <fieldset class="semi-open" name="group-semi[]">

                        <label class="col-md-4 control-label" for="question">Pytanie*</label>

                        <div class="col-md-6">
                            <div class="col-6-lg">
                                <input type="text" class="form-control"
                                       name="questions-semi[<?php echo $questionId; ?>][question]" id=""/>
                            </div>
                        </div>

                        <label class="col-md-4 control-label" for="question">Odpowiedź*</label>

                        <div class="col-md-6">
                            <div class="col-6-lg">
                                <input type="text" class="form-control"
                                       name="questions-semi[<?php echo $questionId; ?>][answer]" id=""/>
                            </div>
                        </div>
                    </fieldset>


                    <fieldset class="closed">

                        <label class="col-md-4 control-label" for="question">Pytanie*</label>

                        <div class="col-md-6">
                            <div class="col-6-lg">
                                <input type="text" class="form-control"
                                       name="questions-closed[<?php echo $questionId; ?>][question]" id=""/>
                            </div>
                        </div>

                        <label class="col-md-4 control-label" for="question">Odpowiedź prawidłowa*: </label>

                        <div class="col-md-6">
                            <div class="col-6-lg">
                                <input type="text" class="form-control"
                                       name="questions-closed[<?php echo $questionId; ?>][answer-correct]"
                                       id=""/>
                            </div>
                        </div>
                        <label class="col-md-4 control-label" for="question">Odpowiedź nieprawidłowa 1*: </label>

                        <div class="col-md-6">
                            <div class="col-6-lg">
                                <input type="text" class="form-control"
                                       name="questions-closed[<?php echo $questionId; ?>][answer-incorrect1]"
                                       id=""/>
                            </div>
                        </div>
                        <label class="col-md-4 control-label" for="question">Odpowiedź nieprawidłowa 2*: </label>

                        <div class="col-md-6">
                            <div class="col-6-lg">
                                <input type="text" class="form-control"
                                       name="questions-closed[<?php echo $questionId; ?>][answer-incorrect2]"
                                       id=""/>
                            </div>
                        </div>
                        <label class="col-md-4 control-label" for="question">Odpowiedź nieprawidłowa 3*: </label>

                        <div class="col-md-6">
                            <div class="col-6-lg">
                                <input type="text" class="form-control"
                                       name="questions-closed[<?php echo $questionId; ?>][answer-incorrect3]"
                                       id=""/>
                            </div>
                        </div>
                    </fieldset>

                </div>
            </div>
            <div class="add-link text-center">
                <a href="" id="add-question" class="button">Dodaj pytanie</a>
            </div>
        </div>

        <div class="text-center">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>


<div class="question-template" style="margin: 5px 100px; border-bottom: 1px solid #dbdbdb; ">
    <div class="form-group">

        <fieldset class="type">
            <label class="col-md-4 control-label" for="question">Wybierz rodzaj pytania*</label>

            <div class="col-md-6">
                <div class="col-6-lg">
                    <select class="form-control" id="">
                        <option value="0">otwarte</option>
                        <option value="1">polotwarte</option>
                        <option value="2">zamkniete</option>
                    </select>
                </div>
            </div>
            <div class="open">

                <label class="col-md-4 control-label" for="question">Pytanie*</label>

                <div class="col-md-6">
                    <div class="col-6-lg">
                        <input type="text" class="form-control"
                               name="questions-open[<?php echo $questionId; ?>][question]"
                               id=""/>
                    </div>
                </div>
            </div>
        </fieldset>

        <fieldset class="semi-open" name="group-semi[]">

            <label class="col-md-4 control-label" for="question">Pytanie*</label>

            <div class="col-md-6">
                <div class="col-6-lg">
                    <input type="text" class="form-control" name="questions-semi[<?php echo $questionId; ?>][question]"
                           id=""/>
                </div>
            </div>

            <label class="col-md-4 control-label" for="question">Odpowiedź*</label>

            <div class="col-md-6">
                <div class="col-6-lg">
                    <input type="text" class="form-control" name="questions-semi[<?php echo $questionId; ?>][answer]"
                           id=""/>
                </div>
            </div>
        </fieldset>


        <fieldset class="closed">

            <label class="col-md-4 control-label" for="question">Pytanie*</label>

            <div class="col-md-6">
                <div class="col-6-lg">
                    <input type="text" class="form-control"
                           name="questions-closed[<?php echo $questionId; ?>][question]"
                           id=""/>
                </div>
            </div>

            <label class="col-md-4 control-label" for="question">Odpowiedź prawidłowa*: </label>

            <div class="col-md-6">
                <div class="col-6-lg">
                    <input type="text" class="form-control"
                           name="questions-closed[<?php echo $questionId; ?>][answer-correct]"
                           id=""/>
                </div>
            </div>
            <label class="col-md-4 control-label" for="question">Odpowiedź nieprawidłowa 1*: </label>

            <div class="col-md-6">
                <div class="col-6-lg">
                    <input type="text" class="form-control"
                           name="questions-closed[<?php echo $questionId; ?>][answer-incorrect1]"
                           id=""/>
                </div>
            </div>
            <label class="col-md-4 control-label" for="question">Odpowiedź nieprawidłowa 2*: </label>

            <div class="col-md-6">
                <div class="col-6-lg">
                    <input type="text" class="form-control"
                           name="questions-closed[<?php echo $questionId; ?>][answer-incorrect2]"
                           id=""/>
                </div>
            </div>
            <label class="col-md-4 control-label" for="question">Odpowiedź nieprawidłowa 3*: </label>

            <div class="col-md-6">
                <div class="col-6-lg">
                    <input type="text" class="form-control"
                           name="questions-closed[<?php echo $questionId; ?>][answer-incorrect3]"
                           id=""/>
                </div>
            </div>
        </fieldset>

    </div>
</div>


<style>
    form .closed, form .semi-open {
        display: none;
    }

    .question-template {
        display: none;
    }

</style>

<script>
    $(document).on('change', 'fieldset select', function () {
        var parent = $(this).parents('.one-question');
        console.log(parent);
        if ($(this).val() == 0) {
            parent.find('.closed, .semi-open').hide();
            parent.find('.open').show();

        }

        if ($(this).val() == 1) {
            parent.find('.semi-open').show();
            parent.find('.closed').hide();
            parent.find('.open').hide();

        }

        if ($(this).val() == 2) {
            parent.find('.closed').show();
            parent.find('.semi-open').hide();
            parent.find('.open').hide();

        }


    });
    setTimeout(function(){
        $('.customize-col-sidebar').css('height', $('body').outerHeight() - $('.customize-navbar').height());
    },2000);

var questionId =  <?php echo $questionId; ?>;
    $('#add-question').click(function (e) {
        questionId++;
        e.preventDefault();
        var template = $('.question-template').clone();
        template.removeClass('question-template').addClass('one-question');
        template.find('select').val(0);

        template.find('input[type="text"]').each(function(index, el){
            $(el).attr('name', $(el).attr('name').replace(new RegExp("\[[0-9]+\]", "i"), '['+questionId+']')); //konieczne zamiana tylko w pierwszym []
        });
        $('.add-link').before(template);
        setTimeout(function(){
            $('.customize-col-sidebar').css('height', $('body').outerHeight() - $('.customize-navbar').height());
        },2000);
    });
</script>
