<div class="panel panel-default customize-panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-pencil"> </span> Edycja testu - <?php echo $test->name; ?>
        </h3>
    </div>
    <div class="panel-body">
        <div class="customize-box-wrapper">
            <div>
                <div class="text-right">
                    <a href="<?php echo $this->url('test', ['action' => 'editData', 'id' => $test->idTest], ['query' => ['test' => $test->idTest]]) ?>">Edytuj
                        dane</a>
                </div>
                <table class="table">
                    <tr>
                        <td>Nazwa:</td>
                        <td>
                            <?php echo $test->name; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Opis:</td>
                        <td>
                            <?php echo $test->description; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Czas wykonania:</td>
                        <td>
                            <?php echo $test->time; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Hasło:</td>
                        <td>
                            <?php echo $test->password; ?>
                        </td>
                    </tr>
                </table>
            </div>
            <div>
                <h4>Pytania </h4>

                <div class="text-right">
                    <a href="<?php echo $this->url('test', ['action' => 'newQuestion', 'id' => $test->idTest]) ?>">Dodaj
                        nowe pytanie</a>
                </div>

                <h5>Otwarte</h5>

                <div>
                    <ul class="list-group">
                        <?php foreach ($questionsOpen as $oQuestion): ?>
                            <li class="list-group-item row" style="margin-left: 5px;">
                                <div class="col-md-8"> <?php echo $oQuestion->text; ?></div>
                                <div class="col-md-4 text-right">
                                    <a href="<?php echo $this->url('test', ['action' => 'editQuestion', 'id' => $oQuestion->idQuestion], ['query' => ['test' => $test->idTest]]) ?>"
                                       class="glyphicon glyphicon-edit"></a>
                                    <a
                                        onclick="return confirm('Czy jesteś pewien, że chcesz usunąć pytanie?')"
                                        href="<?php echo $this->url('test', ['action' => 'deleteQuestion', 'id' => $oQuestion->idQuestion], ['query' => ['test' => $test->idTest]]) ?>"
                                        class="glyphicon glyphicon-remove-circle"></a>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>

                <h5>Półotwarte</h5>

                <div>
                    <ul class="list-group">
                        <?php foreach ($questionsSemi as $sQuestion): ?>
                            <li class="list-group-item row" style="margin-left: 5px;">
                                <div class="col-md-8"><?php echo $sQuestion->text; ?></div>
                                <div class="col-md-4 text-right">
                                    <a href="<?php echo $this->url('test', ['action' => 'editQuestion', 'id' => $sQuestion->idQuestion], ['query' => ['test' => $test->idTest]]) ?>"
                                       class="glyphicon glyphicon-edit"></a>
                                    <a onclick="return confirm('Czy jesteś pewien, że chcesz usunąć pytanie?')"
                                       href="<?php echo $this->url('test', ['action' => 'deleteQuestion', 'id' => $sQuestion->idQuestion], ['query' => ['test' => $test->idTest]]) ?>"
                                       class="glyphicon glyphicon-remove-circle"></a>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>

                <h5>Zamknięte</h5>

                <div>
                    <ul class="list-group">
                        <?php foreach ($questionsClosed as $cQuestion): ?>
                            <li class="list-group-item row" style="margin-left: 5px;">
                                <div class="col-md-8"><?php echo $cQuestion['question']->text; ?></div>
                                <div class="col-md-4 text-right">
                                    <a href="<?php echo $this->url('test', ['action' => 'editQuestion', 'id' => $cQuestion['question']->idQuestion], ['query' => ['test' => $test->idTest]]) ?>"
                                       class="glyphicon glyphicon-edit"></a>
                                    <a onclick="return confirm('Czy jesteś pewien, że chcesz usunąć pytanie?')"
                                       href="<?php echo $this->url('test', ['action' => 'deleteQuestion', 'id' => $cQuestion['question']->idQuestion], ['query' => ['test' => $test->idTest]]) ?>"
                                       class="glyphicon glyphicon-remove-circle"></a>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>