<div class="panel panel-default customize-panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-pencil"> </span> Tworzenie testów
        </h3>
    </div>
    <div class="text-right">
        <a class="btn btn-primary" href="<?php echo $this->url('test', ['action' => 'create']) ?>">Stwórz
            test</a>
    </div>

    <div class="panel-body">
        <div class="customize-box-wrapper table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>#Id</th>
                    <th>Nazwa testu</th>
                    <th>Ogłoszenie</th>
                    <th>Akcja</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($tests as $test) : ?>
                    <tr>
                        <td><?php echo $test->idTest; ?></td>
                        <td class="col-md-6"><?php echo $test->name ?></td>
                        <td class="col-md-3"><a
                                href="<?php echo $this->url('advertisement', ['action' => 'details', 'id' => $test->idAdvertisement]) ?>"><?php echo $test->idAdvertisement; ?></a>
                        </td>
                        <td><a href="<?php echo $this->url('test', ['action' => 'edit', 'id' => $test->idTest]) ?>"
                               class="glyphicon glyphicon-edit"></a>
                            <a href="<?php echo $this->url('test', ['action' => 'delete', 'id' => $test->idTest]) ?>"
                               onclick="return confirm('Usunięcie testu spowoduje usunięcie rozwiązań. Czy jesteś pewien, że chcesz usunąć?')"
                               class="glyphicon glyphicon-remove-circle"></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
