<div class="panel panel-default customize-panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-th"> </span> Ogłoszenia
        </h3>
    </div>
    <div class="text-right">
        <a class="btn btn-primary" href="<?php echo $this->url('advertisement', ['action' => 'create']) ?>">Stwórz
            ogłoszenie</a>
    </div>
    <div class="small text-center">Aby zobaczyć złożone aplikacje - kliknij w wiersz</div>
    <div class="panel-body">
        <div class="customize-box-wrapper table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>#Id</th>
                    <th>Stanowisko</th>
                    <th>Opis</th>
                    <th>Data dodania</th>
                    <th>Akcja</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($advertisements as $advertisement) : ?>
                    <tr class="clicked"
                        onclick="document.location = '<?php echo $this->url('recruitment', ['action' => 'applications', 'id' => $advertisement['idAdvertisement']], ['query' => ['title' => $advertisement['job_title']]]) ?>';">
                        <td><?php echo $advertisement['idAdvertisement']; ?></td>
                        <td class="col-md-3"><?php echo $advertisement['job_title']; ?></td>
                        <td class="col-md-6"><?php echo substr(strip_tags($advertisement['text']), 0, 200); ?></td>
                        <td><?php echo $advertisement['date_added']; ?></td>
                        <td>
                            <a href="<?php echo $this->url('advertisement', ['action' => 'edit', 'id' => $advertisement['idAdvertisement']]) ?>"
                               class="glyphicon glyphicon-edit"></a>
                            <a onclick="return confirm('Usunięcie ogłoszenia spowoduje także usunięcie powiązanych aplikacji. Czy jesteś pewien, że chcesz usunąć?')"  href="<?php echo $this->url('advertisement', ['action' => 'delete', 'id' => $advertisement['idAdvertisement']]) ?>"
                               class="glyphicon glyphicon-remove-circle"></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

