<div class="panel panel-default customize-panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-log-in"> </span> Logowanie
        </h3>
    </div>
    <?php

    $helper = new \Application\View\Helper\Helper();

    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('idUser'));

    ?>

    <fieldset>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('login')); ?>
            <div class="col-md-4">
                <?php echo $this->formInput($form->get('login')); ?>
                <?php echo $helper->formError($this, $form, 'login'); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('password')); ?>
            <div class="col-md-4">
                <?php echo $this->formInput($form->get('password')); ?>
                <?php echo $helper->formError($this, $form, 'password'); ?>
            </div>
        </div>

    </fieldset>
    <div class="text-center">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>


