<div class="panel panel-default customize-panel">
    <div class="panel-heading" style="">
        <h3 class="panel-title" style="">
            <span class="glyphicon glyphicon-envelope"> </span> Napisz do nas
        </h3>
    </div>
    <?php
    $helper = new \Application\View\Helper\Helper();

    $form->prepare();

    echo $this->form()->openTag($form);

    ?>

    <fieldset>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('title')); ?>
            <div class="col-md-4">
                <?php echo $this->formInput($form->get('title')); ?>
                <?php echo $helper->formError($this, $form, 'title'); ?>
            </div>
        </div>


        <div class="form-group">
            <?php echo $this->formLabel($form->get('person')); ?>
            <div class="col-md-4">
                <?php echo $this->formInput($form->get('person')); ?>
                <?php echo $helper->formError($this, $form, 'person'); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <div class="col-md-4">
                <?php echo $this->formInput($form->get('email')); ?>
                <?php echo $helper->formError($this, $form, 'email'); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('text')); ?>
            <div class="col-md-6">
                <?php echo $this->formElement($form->get('text')); ?>
                <?php echo $helper->formError($this, $form, 'text'); ?>
            </div>
        </div>
    </fieldset>
    <div class="text-center">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>


