<div class="panel panel-default customize-panel" xmlns="http://www.w3.org/1999/html">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-th-list"> </span> Składanie aplikacji
        </h3>
    </div>
    <div class="panel-body">
        <h3>Aplikujesz na: <?php echo $advertisement->job_title; ?></h3>

        <h3 class="header-customize">Dane osobowe <a class="glyphicon glyphicon-edit" style="float: right"></a></h3>

        <div class="row customize-box-wrapper">
            <div class="col-md-6  ">
                <table class="table">
                    <tbody>
                    <tr>
                        <td class="customize-label-data">Imię:</td>
                        <td><?php echo $userData->name; ?></td>
                    </tr>
                    <tr>
                        <td class="customize-label-data">Nazwisko:</td>
                        <td><?php echo $userData->surname; ?></td>
                    </tr>
                    <tr>
                        <td class="customize-label-data">Data urodzenia:</td>
                        <td><?php echo $userData->birthday_date; ?></td>
                    </tr>
                    <tr>
                        <td class="customize-label-data">Telefon:</td>
                        <td><?php echo $userData->phone; ?></td>
                    </tr>
                    <tr>
                        <td class="customize-label-data">Adres e-mail:</td>
                        <td><?php echo $userData->email; ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-md-6 col-sm-6">
                <table class="table">
                    <tbody>
                    <tr>
                        <td class="customize-label-data">ulica:</td>
                        <td><?php echo $userAddress->street . ' ' . $userAddress->house_number; ?></td>
                    </tr>
                    <tr>
                        <td class="customize-label-data">kod pocztowy:</td>
                        <td><?php echo $userAddress->postal_code; ?></td>
                    </tr>
                    <tr>
                        <td class="customize-label-data">miasto:</td>
                        <td><?php echo $userAddress->city ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>


        <h3 class="header-customize">Wykształcenie <a class="glyphicon glyphicon-edit" style="float: right"></a></h3>


        <div class="panel-body">
            <div class="customize-box-wrapper">
                <table class="table">
                    <tbody>
                    <?php foreach ($educations as $education) : ?>
                        <tr>
                            <td class="col-md-4"><?php echo $education->school_name; ?></td>
                            <td class="col-md-4"><?php echo $education->description; ?></td>
                            <td class="col-md-5"><?php echo ' od ' . $education->date_from . ' do ' . $education->date_to; ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <h3 class="header-customize">Doświadczenie <a class="glyphicon glyphicon-edit" style="float: right"></a></h3>

        <div class="panel-body">
            <div class="customize-box-wrapper">
                <table class="table">
                    <tbody>
                    <?php foreach ($experiences as $experience) : ?>
                        <tr>
                            <td class="col-md-4"><?php echo $experience->company_name; ?></td>
                            <td class="col-md-4"><?php echo $experience->job_title; ?></td>
                            <td class="col-md-5"><?php echo ' od ' . $education->date_from . ' do ' . $education->date_to; ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <h3 class="header-customize">Umiejętności</h3>


        <div class="panel-body ">
            <div class="customize-box-wrapper">
                <h5 class="text-center">Określ poziom swoich umiejętności wymaganych na stanowisko </h5>
                <div class="text-center" style="color: #3c3c3c; font-size: 12px;">
                    <span style=" color: #ffd655;">★</span>☆☆☆☆ - słaba znajomość
                    <span style=" color: #ffd655;">★★★★★</span> - bardzo dobra znajomość
                </div>
                <?php
                $form->setAttribute('action', $this->url('recruitment', array('action' => 'apply', 'id' => $advertisement->idAdvertisement)));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('idApplication'));

                ?>

                <table class="table">
                    <tbody>
                    <?php foreach ($skills as $skill) : ?>
                        <tr>
                            <td class="col-md-5 text-right"
                                style="vertical-align: middle;">
                                <?php echo $skill->name; ?></td>
                            <td class="col-md-6">

                                <fieldset name="rating-<?php echo $skill->idSkill ?>">
<span class="star-cb-group">
    <input type="radio" id="rating-5-<?php echo $skill->idSkill ?>" name="rating-<?php echo $skill->idSkill ?>"
           value="5"/>
    <label for="rating-5-<?php echo $skill->idSkill ?>">5</label>
    <input type="radio" id="rating-4-<?php echo $skill->idSkill ?>" name="rating-<?php echo $skill->idSkill ?>"
           value="4"/>
    <label for="rating-4-<?php echo $skill->idSkill ?>">4</label>
    <input type="radio" id="rating-3-<?php echo $skill->idSkill ?>" name="rating-<?php echo $skill->idSkill ?>"
           value="3"/>
    <label for="rating-3-<?php echo $skill->idSkill ?>">3</label>
    <input type="radio" id="rating-2-<?php echo $skill->idSkill ?>" name="rating-<?php echo $skill->idSkill ?>"
           value="2"/>
    <label for="rating-2-<?php echo $skill->idSkill ?>">2</label>
    <input checked type="radio" id="rating-1-<?php echo $skill->idSkill ?>" name="rating-<?php echo $skill->idSkill ?>"
           value="1"/>
    <label for="rating-1-<?php echo $skill->idSkill ?>">1</label>
</span>
                                </fieldset>

                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

        </div>
        <div class="text-center">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
