<div class="panel panel-default customize-panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-calendar"> </span> Zaproszenie
        </h3>
    </div>
    <div class="panel-body">
        <div class="customize-box-wrapper">

            <?php if (!is_null($form)): ?>
                <?php
                $helper = new \Application\View\Helper\Helper();

                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('idResult'));
                ?>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('test')); ?>
                    <div class="col-md-6">
                        <?php echo $this->formSelect($form->get('test')); ?>
                        <?php echo $helper->formError($this, $form, 'test'); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo $this->formLabel($form->get('date')); ?>
                    <div class="col-md-6">
                        <?php echo $this->formInput($form->get('date')); ?>
                        <?php echo $helper->formError($this, $form, 'date'); ?>
                    </div>
                </div>

                <div class="text-center">
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            <?php else: ?>
                <div class="text-center">
                    Dla podanego ogłoszenia nie ma jeszcze stworzonego testu. Przejdź do <a
                        href="<?php echo $this->url('test', ['action' => 'create']) ?>" > tworzenia testów </a>.
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('#yourTextFieldIDName').datepicker({
            format: "yyyy-mm-dd",
            viewMode: "day",
            minViewMode: 'day'
        });
</script>