<div class="panel panel-default customize-panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-th-list"> </span> Aplikacje
        </h3>
    </div>
    <div class="panel-body">
        <div class="customize-box-wrapper table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Ogłoszenie</th>
                    <th>Data zgłoszenia</th>
                    <th>Status</th>
                    <th>Akcja</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($applications as $application) : ?>
                    <tr>
                        <td class="col-md-5"><a
                                href="<?php echo $this->url('advertisement', ['action' => 'details', 'id' => $application['Advertisement_idAdvertisement']]); ?>"><?php echo $application['job_title']; ?></a>
                        </td>
                        <td class="col-md-2"><?php echo $application['date_application']; ?></td>
                        <td class="col-md-2"><?php echo(($application['status'] == 'test') ? '<a href="' . $this->url('test', ['action' => 'myTests']) . '"">Test</a>' : $application['status']); ?></td>
                        <td class="col-md-3 customize-action">
                          <a href="<?php echo $this->url('recruitment', ['action' => 'details', 'id'=>$application['idApplication']]) ?>" >Podgląd aplikacji</a> |
                            <a onclick="return confirm('Anulowanie aplikacji spowoduje usunięcie jej z systemu i brak możlwości przywrócenia. Czy jesteś pewien, że chcesz anulować?')"
                               href="<?php echo $this->url('recruitment', ['action' => 'deleteApplication', 'id' => $application['idApplication']]); ?>">
                                Anuluj aplikację
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
